# Generated by Django 5.0.4 on 2024-04-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_remove_task_id_task_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completionStatus',
            field=models.BooleanField(default=False),
        ),
    ]
